#!/usr/bin/env python3
"""
make_report.py — research a topic and save a Markdown report to disk.

Usage:
    python make_report.py "your research topic here"
    python make_report.py "state of local LLMs 2025" --out reports/llms.md

It runs the autonomous web-research agent (search -> read -> refine -> cite),
formats a Markdown report with sources, and writes it to reports/<slug>.md
(or the path you pass with --out). Requires internet; uses your local Ollama
model for synthesis.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)


def _slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return (s[:60] or "report")


def main() -> int:
    ap = argparse.ArgumentParser(description="Research a topic and save a Markdown report.")
    ap.add_argument("topic", help="what to research")
    ap.add_argument("--out", help="output path (default: reports/<slug>-<date>.md)")
    ap.add_argument("--rounds", type=int, default=3, help="max search rounds")
    args = ap.parse_args()

    # Build the LLM + web agent from the existing modules.
    try:
        from core.llm import get_llm
        from core.web_agent import build_default
    except Exception as e:
        print(f"Could not load NEXUS modules: {e}", file=sys.stderr)
        return 2

    llm = None
    try:
        llm = get_llm()
        if not getattr(llm, "is_ready", False):
            print("[warn] Ollama not ready — synthesis will be weaker. "
                  "Start it with `ollama serve`.", file=sys.stderr)
    except Exception:
        pass

    agent = build_default(llm=llm, max_iterations=args.rounds)
    if agent is None:
        print("Web-research agent unavailable (research modules missing).", file=sys.stderr)
        return 2

    print(f"Researching: {args.topic!r} ...", file=sys.stderr)
    result = agent.research(
        args.topic,
        on_progress=lambda m: print(f"  {m}", file=sys.stderr),
    )

    # Assemble the Markdown report.
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Research Report: {args.topic}",
        "",
        f"*Generated by NEXUS on {now}*",
        "",
        "## Summary",
        "",
        result.answer.strip() or "_No findings._",
        "",
        "## Sources",
        "",
    ]
    if result.sources:
        for i, s in enumerate(result.sources, 1):
            lines.append(f"{i}. [{s.title or s.url}]({s.url})")
    else:
        lines.append("_No sources collected._")
    lines += [
        "",
        "---",
        f"*Search rounds: {result.iterations} · queries: "
        f"{'; '.join(result.queries)}*",
        "",
    ]
    report = "\n".join(lines)

    # Write it out.
    out = args.out or os.path.join(
        ROOT, "reports", f"{_slug(args.topic)}-{_dt.date.today()}.md")
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\nReport saved: {out}")
    print(f"  {len(result.sources)} source(s), {result.iterations} search round(s).")
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
